language: go
go:
 - 1.8
 - tip

before_install:
 - go get github.com/mattn/goveralls

install:
  - go get -d -v ./...
  - go build -v -o golinters cmd/golinters/main.go

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci

after_success:
  - export GOLINTERS_OUTPUT=output-$(date +%Y-%m-%d-%H%M%S-%Z).html
  - ./golinters -output=$GOLINTERS_OUTPUT
