language: go
go:
 - 1.8
 - tip

before_install:
 - go get github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci

after_success:
  - pwd
  - $TRAVIS_BUILD_DIR/golinters -output=output-$(date +%Y-%m-%d-%H%M%S-%Z).html
